Dev/TrainCommander/TrainCommander/Controllers/CheckoutController.cs
using Newtonsoft.Json;
using Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using TrainCommander.Models;
using TrainCommander.Paypal;

namespace TrainCommander.Controllers
{
    public class CheckoutController : Controller
    {
        // GET: Checkout
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cart()
        {
            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"];
            }
            List<SuperTripViewModel> cart;
            if (Session["Cart"] != null)
            {
                cart = (List<SuperTripViewModel>)Session["Cart"];
            }
            else
            {
                cart = new List<SuperTripViewModel>();
            }

            ListCarViewModel model = new ListCarViewModel();
            model.superTripViewModel = cart;
            return View("Cart", model);
        }

        public ActionResult Confirmation()
        {
            ConfirmationViewModel model = new ConfirmationViewModel();
            List<SuperTripViewModel> cart;
            CoordonneesViewModel coordonneesViewModel = new CoordonneesViewModel();

            if (Session["Cart"] != null)
            {
                cart = (List<SuperTripViewModel>)Session["Cart"];
                foreach (var trip in cart)
                {
                    model.TotalPrice += trip.Price * trip.Quantity;
                }
            }
            else
            {
                ListCarViewModel modelEmpty = new ListCarViewModel();
                cart = new List<SuperTripViewModel>();
                modelEmpty.superTripViewModel = cart;
                return View("Cart", modelEmpty);
            }

            if (Request.IsAuthenticated)
            {
                coordonneesViewModel.Email = User.Identity.Name;
            }

            model.superTripViewModel = cart;
            model.coordonneesViewModel = coordonneesViewModel;
            Session["TotalPrice"] = model.TotalPrice;
            return View("Confirmation", model);
        }

        public ActionResult Buy(ConfirmationViewModel model)
        {
            return View("Command");
        }

        public ActionResult CreatePayment(ConfirmationViewModel model)
        {
            //need model state valid + redirect to action if error
            Session["Command"] = model;
            var payment = PayPalPaymentService.CreatePayment(GetBaseUrl(), "sale", (double)Session["TotalPrice"]);
            return Redirect(payment.GetApprovalUrl());

        }

        public ActionResult PaymentCancelled()
        {
            Session["Command"] = null;
            TempData["Error"] = @langage.errorPayment;
            return RedirectToAction("Cart");
        }

        public ActionResult PaymentSuccessful(string paymentId, string token, string PayerID)
        {
            // Execute Payment
            var payment = PayPalPaymentService.ExecutePayment(paymentId, PayerID);
            Session["Cart"] = null;

            ConfirmationViewModel confirmModel = (ConfirmationViewModel)Session["Command"];

            var toAddress = confirmModel.coordonneesViewModel.Email;
            var fromAddress = "ticket@train-commander.fr";
            var subject = "Your Ticket";
            var message = new StringBuilder();
            int j = 0;
            foreach (var trip in confirmModel.superTripViewModel) //make disctionnary trip, people
            {
                for (var i = 0; i < trip.Quantity; i++)
                {
                    message.Append("Ticket for trip from : " + trip.DepartureStation + " to " + trip.ArrivalStation + "\n");
                    message.Append("Departure date : " + trip.DepartureDate + " Arrival date " + trip.ArrivalDate + "\n");
                    message.Append("Ticket For : " + confirmModel.personneViewModel[j + i].FirstName + confirmModel.personneViewModel[j + i].LastName + "\n");

                }
                j++;
            }

            //start email Thread
            var tEmail = new Thread(() => SendEmail(toAddress, fromAddress, subject, message.ToString()));
            tEmail.Start();

            //TODO mail success + save database
            return RedirectToAction("Buy");
        }

        public string GetBaseUrl()
        {
            return Request.Url.Scheme + "://" + Request.Url.Host + ":44387";
        }

        public ActionResult AddToCart()
        {
            List<SuperTripViewModel> cart;
            if (Session["Cart"] != null)
            {
                cart = (List<SuperTripViewModel>)Session["Cart"];
            }
            else
            {
                cart = new List<SuperTripViewModel>();
            }
            int index = int.Parse(Request.QueryString["index"]);
            List<SuperTripViewModel> listPropose = (List<SuperTripViewModel>)Session["listProposition"];
            if (listPropose != null)
            {
                SuperTripViewModel choosenTrip = listPropose[index];
                Session["listProposition"] = null;
                cart.Add(choosenTrip);
            }
            Session["Cart"] = cart;
            ListCarViewModel model = new ListCarViewModel();
            model.superTripViewModel = cart;
            return View("Cart", model);
        }

        public ActionResult AddToCartjson(int index)
        {
            List<SuperTripViewModel> cart;
            if (Session["Cart"] != null)
            {
                cart = (List<SuperTripViewModel>)Session["Cart"];
            }
            else
            {
                cart = new List<SuperTripViewModel>();
            }
            List<SuperTripViewModel> listPropose = (List<SuperTripViewModel>)Session["listProposition"];
            if (listPropose != null)
            {
                SuperTripViewModel choosenTrip = listPropose[index];
                cart.Add(choosenTrip);
            }
            Session["Cart"] = cart;
            return Json(new { result = "ok" });
        }

        public ActionResult DeleteAll()
        {
            Session["Cart"] = null;
            return RedirectToAction("Cart", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteOne(int index)
        {
            List<SuperTripViewModel> cart = (List<SuperTripViewModel>)Session["Cart"];
            cart.RemoveAt(index);
            Session["Cart"] = cart;
            return Json(new { result = "ok" });
        }

        public ActionResult SaveCart()
        {
            if (Request.IsAuthenticated)
            {
                List<SuperTripViewModel> cart = (List<SuperTripViewModel>)Session["Cart"];
                string jsonString = JsonConvert.SerializeObject(cart);
                System.Diagnostics.Debug.WriteLine(jsonString);
                //call api here
                return Json(new { result = "ok" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { result = "ok" }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult AddQuantity(int index)
        {
            List<SuperTripViewModel> cart = (List<SuperTripViewModel>)Session["Cart"];
            cart[index].Quantity += 1;
            Session["Cart"] = cart;
            return Json(new { result = "ok" });
        }

        [HttpPost]
        public ActionResult RemoveQuantity(int index)
        {
            List<SuperTripViewModel> cart = (List<SuperTripViewModel>)Session["Cart"];
            cart[index].Quantity -= 1;
            Session["Cart"] = cart;
            return Json(new { result = "ok" });
        }

        [HttpPost]
        public ActionResult ChangeQuantity(int index, int quantity)
        {
            List<SuperTripViewModel> cart = (List<SuperTripViewModel>)Session["Cart"];
            if (quantity > 0)
            {
                cart[index].Quantity = quantity;
            }
            else
            {
                if (cart.Count != 0)
                {
                    cart.RemoveAt(index);
                }
                else
                {
                    cart = null;
                }
            }
            Session["Cart"] = cart;
            return Json(new { result = "ok" });
        }

        public void SendEmail(string toAddress, string fromAddress,
                      string subject, string message)
        {
            try
            {
                using (var mail = new MailMessage())
                {
                    const string email = "username@train-commander.fr";
                    const string password = "passwordMail2016!";

                    var loginInfo = new NetworkCredential(email, password);


                    mail.From = new MailAddress(fromAddress);
                    mail.To.Add(new MailAddress(toAddress));
                    mail.Subject = subject;
                    mail.Body = message;
                    mail.IsBodyHtml = true;

                    try
                    {
                        using (var smtpClient = new SmtpClient(
                                                         "smtp.mail.train-commander.fr", 465))
                        {
                            smtpClient.EnableSsl = true;
                            smtpClient.UseDefaultCredentials = false;
                            smtpClient.Credentials = loginInfo;
                            smtpClient.Send(mail);

Dev/TrainCommander/TrainCommander/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainCommander.Models;
using Newtonsoft.Json;
using PayPal.Api;
using TrainCommander.Paypal;
using System.Text;
using System.Net;

namespace TrainCommander.Controllers
{
    public class TripController : Controller
    {
        // GET: Trip
        public ActionResult Index()
        {
            TripFormAndSuperTripViewModel model = new TripFormAndSuperTripViewModel();
            model.tripFormModel = new TripFormModel(); // maybe add session here for get last search
            return View(model);
        }

        [HttpPost]
        public ActionResult GetTrain(TripFormModel model)
        {
            List<SuperTripViewModel> result = new List<SuperTripViewModel>();
            //model.DateOneWay = DateTime.ParseExact(model.DateOneWay.ToString(), "dd/MM/yyyy", null);
            /*string[] keys = Request.Form.AllKeys;
            for (int i = 0; i < keys.Length; i++)
            {
                System.Diagnostics.Debug.WriteLine(keys[i] + ": " + Request.Form[keys[i]] + "<br>");
            }*/
            if (ModelState.IsValid)
            {
                //System.Diagnostics.Debug.WriteLine("ici");
                //call API

                result = GetTripFromApi(model.DepartOrArrivalOneWay, model.DepartureStation, model.ArrivalStation, model.DateOneWay, model.HourOneWay);
                foreach (var trip in result)
                {
                    trip.isReturn = false;
                }

                if (model.TripWay == false)
                {
                    List<SuperTripViewModel> tmp = GetTripFromApi(model.DepartOrArrivalReturn, model.ArrivalStation, model.DepartureStation, (DateTime) model.DateReturn, model.HourReturn);
                    foreach(var trip in tmp)
                    {
                        trip.isReturn = true;
                        result.Add(trip);
                    }
                }
            }

            Session["listProposition"] = result;

            TripFormAndSuperTripViewModel modelReturn = new TripFormAndSuperTripViewModel();
            modelReturn.tripFormModel = model;
            modelReturn.superTripViewModel = result;


            return View("Index", modelReturn);
        }

        public List<SuperTripViewModel> GetTripFromApi(string departOrArrival, string departureStation, string arrivalStation, DateTime dateTrip, int hour)
        {
            string convert_de_porc;

            if (departOrArrival == "departTo")
            {
                convert_de_porc = "false";
            }
            else
            {
                convert_de_porc = "true";
            }
            TimeSpan ts = new TimeSpan(hour, 00, 0);
            DateTime dateWithHour = dateTrip.Date + ts;

            string date = dateWithHour.ToString("yyyyMMddHHmmss");
            date = date.Replace(@"/", string.Empty);
            date = date.Replace(@" ", string.Empty);
            date = date.Replace(":", string.Empty);

            string sURL = "http://localhost:51675/api/trips/GetSuperTrips/" + departureStation + "/" + arrivalStation + "/" + date + "/" + convert_de_porc;

            WebRequest wrGETURL = WebRequest.Create(sURL);

            HttpWebRequest request = wrGETURL as HttpWebRequest;

            HttpWebResponse response = (HttpWebResponse)request.GetResponse();

            WebHeaderCollection header = response.Headers;

            var encoding = ASCIIEncoding.ASCII;

            string apiJson;

            using (var reader = new System.IO.StreamReader(response.GetResponseStream(), encoding))
            {
                apiJson = reader.ReadToEnd();

            }

            return JsonConvert.DeserializeObject<List<SuperTripViewModel>>(apiJson);
        }

        public ActionResult Promo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TestPaypal()
        {
            var config = ConfigManager.Instance.GetProperties();

            // Use OAuthTokenCredential to request an access token from PayPal
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();

            var apiContext = new APIContext(accessToken);

            // A transaction defines the contract of a payment - what is the payment for and who is fulfilling it. 
            var transaction = new Transaction()
            {
                amount = new Amount()
                {
                    currency = "USD",
                    total = "7",
                    details = new Details()
                    {
                        shipping = "1",
                        subtotal = "5",
                        tax = "1"
                    }
                },
                description = "This is the payment transaction description.",
                item_list = new ItemList()
                {
                    items = new List<Item>()
                    {
                        new Item()
                        {
                            name = "Item Name",
                            currency = "USD",
                            price = "1",
                            quantity = "5",
                            sku = "sku"
                        }
                    }
                },
                invoice_number = new Random().Next(999999).ToString()
            };

            // A resource representing a Payer that funds a payment.
            var payer = new Payer()
            {
                payment_method = "paypal",
                payer_info = new PayerInfo
                {
                    email = "test@email.com"
                }
            };

            // A Payment resource; create one using the above types and intent as `sale` or `authorize`
            var payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = new List<Transaction>() { transaction }
            };

            // Create a payment using a valid APIContext
            var createdPayment = payment.Create(apiContext);

            return View("Index", "Home");
        }
    }
}

Dev/TrainCommander/TrainCommander/Views/Checkout/Cart.cshtml
@using TrainCommander.Models
@model ListCarViewModel

@section head{
    <title>@langage.cart</title>
}

@section scripts{
    <script type="text/javascript">

        jQuery(document).ready(function (jQuery) {

            $(".btnQuantityLess").click(function () {
                var index = $(this).data("id");
                var price = $(this).data("price");
                var quantity = parseInt($("#inputQuantity" + index).val());
                quantity --;
                var data = { index: index, quantity: quantity };
                ajaxLauncherPostJson(data, '@Url.Action("ChangeQuantity", "Checkout")', successChangeQuantity(index, price, quantity));
            });

            $(".btnQuantityPlus").click(function () {
                var index = $(this).data("id");
                var price = $(this).data("price");
                var quantity = parseInt($("#inputQuantity" + index).val());
                quantity ++;
                var data = { index: index, quantity: quantity };
                ajaxLauncherPostJson(data, '@Url.Action("ChangeQuantity", "Checkout")', successChangeQuantity(index, price, quantity));
            });

            function successChangeQuantity(index, price, quantity) {
                var priceTxt = $("#price" + index);
                $("#inputQuantity" + index).val(quantity);
                var newPrice = price * quantity;
                if (newPrice <= 0) {
                    priceTxt.text("0");
                    $("#divCart" + index).hide();
                    var count = parseInt($("#contentBoxTrip").data("count"));
                    count--;
                    if (count == 0) {
                        location.reload();
                    }
                    else {
                        $("#contentBoxTrip").data("count", count);
                    }
                }
                else {
                    priceTxt.text(price * quantity);
                }
            }

            $(".inputQuantity").change(function () {
                var index = $(this).data("id");
                var price = $(this).data("price");
                var quantity = parseInt($(this).val());
                var data = { index: index, quantity: quantity };
                ajaxLauncherPostJson(data, '@Url.Action("ChangeQuantity", "Checkout")', successChangeQuantity(index, price, quantity));
            });

            $("#saveCartBtn").click(function () {
                console.log("ici");
                $.ajax({
                    type: 'GET',
                    contentType: 'application/json; charset=utf-8',
                    url: '@Url.Action("SaveCart", "Checkout")',
                    success: function (data) {
                        /*console.log(data);
                        console.log(data.result);*/
                        if (data.result == "notConnected") {
                            /*$('#failureNotificationLogin').text("You need to be logged for saving your cart");*/
                            $('#logInBtn').trigger('click');
                        }
                        else if (data.result == "ok") {
                            $('#modalText').text("You have sucessfully sauvegarded your cart");
                            $('#modalBtn').trigger('click');
                        }
                    },
                    error: function (xhr, err) {
                        if (xhr.readyState != 0 || xhr.status != 0) {
                            alert("readyState: " + xhr.readyState + "  status: " + xhr.status + "\n\nresponseText: " + xhr.responseText);
                        }
                    }
                });
            });
        });
    </script>
}

<div class="container marginB100">
    <div class="txtAlignC">
        <h2>@langage.cart :</h2>
    </div>
    @if (Model != null && Model.superTripViewModel != null)
    {
        int i = 0;
        if (Model.superTripViewModel.Count != 0)
        {
            <div class="contentBox" id="contentBoxTrip" data-count='@Model.superTripViewModel.Count'>
                @foreach (var trip in Model.superTripViewModel)
                {
                    <div class="row marginB30" id='@("divCart"+i)'>
                        <div class="col-xs-12">
                            <div class="horizontalSeparate"></div>
                            <div class="row tripBox">
                                <div class="col-xs-2">
                                    <p>
                                        @trip.DepartureDate.Day.ToString("00")/@trip.DepartureDate.Month.ToString("00")/@trip.DepartureDate.Year : @trip.DepartureDate.Hour.ToString("00"):@trip.DepartureDate.Minute.ToString("00")<br />
                                        @trip.ArrivalDate.Day.ToString("00")/@trip.ArrivalDate.Month.ToString("00")/@trip.ArrivalDate.Year : @trip.ArrivalDate.Hour.ToString("00"):@trip.ArrivalDate.Minute.ToString("00")
                                    </p>
                                </div>
                                <div class="col-xs-5">
                                    <p>
                                        @trip.DepartureStation<br />
                                        @trip.ArrivalStation
                                    </p>
                                </div>
                                <div class="col-xs-2">
                                    <p>
                                        @if (trip.IsDirect)
                                        {
                                            @:Direct
                                        }
                                        else
                                        {
                                            @:Via :
                                }
                                        <br />
                                        <span class="glyphicon glyphicon-time"></span>  @(Math.Floor((trip.ArrivalDate - trip.DepartureDate).TotalHours).ToString("00")) : @(((trip.ArrivalDate - trip.DepartureDate).TotalMinutes % 60).ToString("##"))
                                    </p>
                                </div>
                                <div class="col-xs-3">
                                    <p><span id='@("price"+i)'>@(trip.Price*trip.Quantity)</span> €</p>
                                    <div class="row">
                                        <div class="col-xs-3">
                                            <button type="button" class="btnQuantityLess btn btn-default" data-id='@i' data-price=@trip.Price>-</button>
                                        </div>
                                        <div class="col-xs-6">
                                            <input type="text" class="formControl txtAlignC inputQuantity" data-id='@i' data-price=@trip.Price id='@("inputQuantity"+i)' value="@trip.Quantity" />
                                        </div>
                                        <div class="col-xs-3">
                                            <button type="button" class="btnQuantityPlus btn btn-default" data-id='@i' data-price=@trip.Price >+</button>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    i++;
                }
            </div>
            <div class="btnCartDiv txtAlignC">
                @Html.ActionLink(@langage.deleteAll, "DeleteAll", "Checkout", new { @class = "btn btn-default" })
                @Html.ActionLink(@langage.buy, "Confirmation", "Checkout", new { }, new { @class = "btnAction" })
                <button type="button" class="btn btn-default" id="saveCartBtn">@langage.saveCart</button>
            </div>
        }
        else
        {
            <div class="txtAlignC marginT50">
                <h2 class="marginB30">Votre Panier est encore vide :( ! </h2>
                @Html.ActionLink(@langage.reserv, "Index", "Trip", new { }, new { @class = "btnAction" })
                @Html.ActionLink(@langage.promos, "Promo", "Trip", new { }, new { @class = "btnAction" })
            </div>
        }
    }


</div>

Dev/TrainCommander/TrainCommander/Views/Checkout/Command.cshtml
@model TrainCommander.Models.MailModels
@{
    ViewBag.Title = "Contact";
}
@section head{
    <title>@langage.command</title>
}
<div class="container">
    <div class="containerText">
        <h2>@langage.sucessPay</h2>
        <p>@langage.receiveMailCanPrint</p>
        <button type="button" class="btnAction">@langage.printTicket</button>
    </div>
</div>
